name: Build user scripts

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun run build

      - name: Create new branch
        run: |
          git checkout -b build-output
          git add .
          git commit -m "Build output"
          git push origin build-output
