name: Build and Release user scripts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build user scripts
        run: bun run build

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        workspace:
          - fandom-debloat
          - idrlabs-solver
          - samequizy-autoplay
          - samequizy-solver

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release for ${{ matrix.workspace }}
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          replacesArtifacts: true
          tag: ${{ matrix.workspace }}
          artifacts: "release.tar.gz,packages/${{ matrix.workspace }}/dist/script.user.js"