name: Build user scripts

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        workspace:
          - fandom-debloat
          - idrlabs-solver
          - samequizy-autoplay
          - samequizy-solver

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun run build

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "release.tar.gz,packages/${{ matrix.workspace }}/script.user.js"
