name: Build user scripts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install
      
      - name: Build all packages
        run: bun run build

      - name: Deploy built files to result branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout build-result
          git add dist
          git commit -m "Build and deploy to build-result"
          git push origin build-result --force
