name: Build user scripts

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun run build

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "release.tar.gz,**/script.user.js"
