name: Build user scripts

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        workspace:
          - fandom-debloat
          - idrlabs-solver
          - samequizy-autoplay
          - samequizy-solver

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.workspace }}-user-script
          path: packages/${{ matrix.workspace }}/dist
